### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by dplong** [arachnys/athenapdf#134]
I can view my source .html with Chrome, use wget to retrieve it, and convert it with wkhtmltopdf. However, when I use athenapdf, I get ERR_CONNECTION_REFUSED. Any idea why? I'm serving it via the builtin HTTP server in Jekyll.

Here's the wkhtmltopdf command that works:
> wkhtmltopdf --disable-external-links  http://localhost/test.html test.pdf

Here's the athenapdf command that doesn't:
> sudo docker run --security-opt seccomp:unconfined --rm -v $(pwd):/converted/ arachnysdocker/athenapdf athenapdf http://localhost/test.html test.pdf

This is the error I get from athenapdf:
> Failed to load: -102 ERR_CONNECTION_REFUSED (http://localhost/test.html)

**Comment by MrSaints** [comment]
Ah yeah, that's something we should probably include in the documentation. But, as it is running inside Docker, you can't really convert _localhost_, as it would point to _localhost_ within the Docker container's network. That is, unless you run it with `--network="host"`. Otherwise, replace `localhost` with your LAN / internal IP.

**Comment by dplong** [comment]
I got it to work with the IP address and --network="host". However, 127.0.0.1 didn't work. I'm going with the --network="host" solution. 

BTW, athenapdf takes 30 seconds to convert my three .html files whereas mkhtmltopdf takes ten minutes.  BIG improvement, plus athenapdf doesn't split a line across a page break like wkhtmltopdf does occasionally. There are other problems, though, that I'll take up in separate issues.
