### ISSUE TITLE
Webfonts not rendering

### ISSUE THREAD

**Issue by jacobwgillespie** [arachnys/athenapdf#4]
I attempted to convert the following into a PDF: https://gist.github.com/jacobwgillespie/de11f4100154042b8b8d615230594acd.

This is the resulting PDF: [resume.pdf](https://github.com/arachnys/athenapdf/files/209573/resume.pdf), and it looks like it's missing the webfonts from the stylesheet.

**Comment by MrSaints** [comment]
@jacobwgillespie thanks for reporting the issue.

I've tried it on my side, and it seems to be caused by FOIT (flash of invisible text). It saved fine on the second attempt, although I know, this is not ideal.

There's an option to increase the _delay_ before saving (it's `-D` or `--delay`). It's set to 200ms by default, but I think if you raise it to 300ms, it should address similar problems in the future.

[295118aa7843e73ee4bd74c1c69547c1c1d24eee.pdf](https://github.com/arachnys/athenapdf/files/209910/295118aa7843e73ee4bd74c1c69547c1c1d24eee.pdf)

**Comment by jacobwgillespie** [comment]
Cool, thanks!

**Comment by jacobwgillespie** [comment]
It seems this still may be an issue - I ran it with `-D 5000` just to be certain.  Fonts are now showing up, but it doesn't look like the webfonts are being picked up.

Here's from Athena: [resume.pdf](https://github.com/arachnys/athenapdf/files/220215/resume.pdf)

And here's from wkhtmltopdf: [resume.pdf](https://github.com/arachnys/athenapdf/files/220219/resume.pdf)

**Comment by MrSaints** [comment]
Interesting, it appears to be working on my side.

Can you try a `docker pull arachnysdocker/athenapdf` ?

[295118aa7843e73ee4bd74c1c69547c1c1d24eee.pdf](https://github.com/arachnys/athenapdf/files/220623/295118aa7843e73ee4bd74c1c69547c1c1d24eee.pdf)

**Comment by jacobwgillespie** [comment]
Yep, that fixed it - I was sure I updated but apparently I hadn't.  It works now even without the delay flag.  Thanks!
