### ISSUE TITLE
Conversion process hit the URL twice

### ISSUE THREAD

**Issue by neofreko** [arachnys/athenapdf#53]
I have a setup which will generate an URL with one time token access. I was wondering why I always fail in generating PDF. My log says I have two requests from Athena. The first one, yield in HTTP 200. And another one (of which the token no longer valid), yield 401.

Apparently this line https://github.com/arachnys/athenapdf/blob/master/weaver/converter/athenapdf/athenapdf.go#L45
actually hit my URL before the actual conversion task. 

```
log.Printf("[AthenaPDF] converting to PDF: %s\n", s.GetActualURI())
```

Of course, switching `GIN_MODE` to `release` immediately fixed my issue (after hours of frustration). Maybe we can log `s.URI` instead of calling `getActualURI`

**Comment by MrSaints** [comment]
Hey @neofreko, apologies for the frustration you had to go through for it to work nicely.

Unfortunately, I'm not convinced that the aforementioned line of code is the reason for generating an additional HTTP request, nor am I convinced that setting `GIN_MODE` to `release` is the solution to your problem. Something would be amiss otherwise.

Firstly, `s.GetActualURI()` never makes any HTTP request. In fact, it uses `s.URI` sometimes (and it probably does in your case). It was created so that we can retain original URLs for conversions that cannot not be done remotely due to the content-type. It's not the greatest of designs, but it'll be refactored soon.

Secondly, setting `GIN_MODE` to `release` only influences the logging, and stats behaviour. And neither of those should be making an additional HTTP request to the conversion source. I can confirm that this is at least the case on my end.

In essence, logging `s.URI` instead of `s.GetActualURI()` will not make any difference.

The real source of the _extra_ HTTP request is from : https://github.com/arachnys/athenapdf/blob/ed68bc1abb6f38059e60cb47384878ab9fe2c417/weaver/converter/source.go#L111

It was introduced to allow us to do some pre-processing prior to the actual conversion (e.g. if the conversion source needs to be downloaded, and if the content-type is acceptable - in the future).

Unfortunately, there is not simple config to turn this off at the moment. However, if you don't mind getting your hands a little bit dirty, try changing:

```go
func convertByURLHandler(c *gin.Context) {
	s := c.MustGet("statsd").(*statsd.Client)
	r, ravenOk := c.Get("sentry")

	url := c.Query("url")
	if url == "" {
		c.AbortWithError(http.StatusBadRequest, ErrURLInvalid).SetType(gin.ErrorTypePublic)
		s.Increment("invalid_url")
		return
	}

	ext := c.Query("ext")

	source, err := converter.NewConversionSource(url, nil, ext)
	if err != nil {
		s.Increment("conversion_error")
		if ravenOk {
			r.(*raven.Client).CaptureError(err, map[string]string{"url": url})
		}
		c.Error(err)
		return
	}

	conversionHandler(c, *source)
}
```

To something like:

```go
func convertByURLHandler(c *gin.Context) {
	s := c.MustGet("statsd").(*statsd.Client)

	url := c.Query("url")
	if url == "" {
		c.AbortWithError(http.StatusBadRequest, ErrURLInvalid).SetType(gin.ErrorTypePublic)
		s.Increment("invalid_url")
		return
	}

	source := converter.ConversionSource{URI: url}

	conversionHandler(c, source)
}
```

The above will bypass the pre-processing entirely by giving the raw `ConversionSource` struct.

Let me know if that helps or if you have any other questions :smile:

And once again, my apologies for the inconveniences you had to go through.

**Comment by neofreko** [comment]
@MrSaints 
LOL, so much for my wild guess :p

No worries, I've adjusted my own backend a bit to work around above issue. Keeping a fork of athenapdf is a bit too much for me at the moment. Hopefully, above issue can be addressed properly in the future.

Thank you for this fine software :). Leanest converter I've found so far.

**Comment by chripede** [comment]
Are there any plans to make this configurable. We use Athena for report generating, something that is often quite costly. Hitting the URL twice is making everything take much longer than needed.

**Comment by borkdude** [comment]
I've hit the same issue with a one time token access.

**Comment by MrSaints** [comment]
Just an update. In v3, the service assembly will on longer _hit a target URI twice_.

The only caveat however, is that a **mime type will have to be specified or a fetcher**. Otherwise, there is no way to: 1. know what converter we should use if none is specified, and 2. inform the converter beforehand what the input file type is (which is essential in some cases).

I would advise against using a fetcher if a site has lots of assets that are linked using relative URIs. 
To a certain degree, this _improvement_ may also open up some security loopholes. The nice thing about the service performing a pre-conversion check (to fetch metadata) in the old version is that it unintentionally acted as a gatekeeper / border control.
I observed this with our demo site which blocked a lot of undesired conversions before it even hit the converter itself.
