### ISSUE TITLE
Support for page with authentication

### ISSUE THREAD

**Issue by sum1190** [arachnys/athenapdf#6]
Hi,

very great project! Is there a support for authentication (or session) on web page that require username/password?

Thanks :)

**Comment by MrSaints** [comment]
Hey @sum1190, thank you. We're glad you like it.

It should be able to support basic auth.

Have you tried converting with the following syntax `http://user:pass@website.com` ?

**Comment by sum1190** [comment]
Unfortunately not, the page that I was testing is from a private project written in PHP with the Yii2 framework, and the method that you've tell to me doesn't work :/

**Comment by MrSaints** [comment]
Apologies for the late response @sum1190.

Ah I see. It's not a basic auth. In that case, we do not currently support it.

We can however, add the ability for the _converter_ to run using a custom cookie jar (session) if that helps. Otherwise, I'd suggest adding a basic auth endpoint if you'd like to convert a protected page (or perhaps a page that may be accessible by a unique security token).

In theory, we can make it automatically fill up forms, submit, and convert, but it'd make the CLI app unnecessarily complex. For the aforementioned case, I'd suggest you look into http://www.nightmarejs.org/. 

Hope that helps, and sorry 😞

**Comment by sum1190** [comment]
I think that support for SESSION auth can be an useful idea ;)

PS. Thank you for the link http://www.nightmarejs.org/ , I've never seen it before

**Comment by roberto-robles** [comment]
+1

**Comment by cliffom** [comment]
@MrSaints We are currently testing in an environment that is protected behind basic auth. However, the usernames used in our environment are email addresses and thus need to be URL encoded. We pass the `url` parameter to the web service URL encoded but your service is attempting a GET request for the document on an unencoded URL and is met with an unauthorized response. Please advise.
