### ISSUE TITLE
weaver: Multiple files web page.

### ISSUE THREAD

**Issue by andresinaka** [arachnys/athenapdf#80]
Hi guys, I'm thinking of using weaver for an html to pdf conversion. The html file I'm going to convert is not hosted in a webserver so I was planning on sending it to the server using the `convertByFileHandler`. And a curl similar to:

```
 curl -v -F file="@index.html" http://localhost:8080/convert?auth=arachnys-weaver
```

But of course, I can't include css files nor images doing this...is there a way of sending a whole webpage (css, js and html) that I'm not seeing??

**Comment by MrSaints** [comment]
You have two options (out of the top of my head):-

- Inline all your assets: I'm unsure if there's an 'automated' way out there to do this, but the resulting file size might be huge because of the base64 images
- Save the page as MHTML: on Chrome, you might have to enable this feature on `chrome://flags/`, but once you save the page as MHTML, you should be able to convert it to PDF by passing an additional `?ext=mhtml` parameter

Let me know if that helps.
