### ISSUE TITLE
Page number in a footer

### ISSUE THREAD

**Issue by fsauter** [arachnys/athenapdf#94]
Hi guys,

can you give me an example how to display the page number with a footer? #42 seems to go into the right direction but I do not get what "relying on stamping / watermarking to achieve headers, and footers" means @MrSaints :-(. Any code examples?

Cheers Florian

**Comment by MrSaints** [comment]
Hi @fsauter,

Essentially, we generate two documents which we layer together. Again, as my comment in that issue mentions, it's not so straightforward, but it does allow for more granular control over the final output.

---

The first document - let's call it the main layer - comprise of the core content. The second document is the header / footer layer.

We generate the main layer first without headers, and footers. But, we include padding on the page to account for them. Then, we use [GhostScript](https://www.ghostscript.com/) (it should be available as a package in most distros) to get the page numbers:

```
gs <flags> -c "(<filename>) (r) file runpdfbegin pdfpagecount = quit" 
```

There are lots of other FOSS that can retrieve the total number of pages from a PDF document if you do not want to go down the GhostScript route.

Once you have the total number of pages (N), it's just a matter of generating a HTML document which when converted to PDF, will have N number of pages. Here are some helper CSS classes you can use:

```
.page {
  page-break-after: always;
  position: relative;
}

.header, .footer {
  position: absolute;
  text-align: center;
  width: 100%;
}

.header {
  top: 0;
}

.footer {
  bottom: 0;
}
```

You can generate the document using a template engine of your choice, depending on your language, and as long as they support loops (because you need to create N segments with the `.page` class).

Once it's generated, and converted to PDF, you can use either [PDFTK](https://www.pdflabs.com/docs/pdftk-version-history/) or [PDFBox](https://pdfbox.apache.org/) to merge the layers together.

Example:

```
pdftk layer1.pdf multibackground layer2.pdf output merged.pdf
```

I hope that helps! :smile:

**Comment by fsauter** [comment]
Hey @MrSaints 

thank you so much for the explanation! So if I want to use Athenapdf as Microservice (weaver) I would need a second service, that converts those two layers and than send the result to the user... that sounds as a lot of work :-/

With wickedpdf (wrapper for wkhtmltopdf) I can use a javascript snippet to achieve the page numbers (https://github.com/mileszs/wicked_pdf#page-numbering). The same concept would not be possible with athena or?

And another idea I had: can we say we know the total height of one A4 PDF page with javascript? So I could add a page number by dividing the total viewport height by a PDF page height using javascript... would that be somehow possible (unfortunately I'm not aware of all the dpi/pts/pixel differences)?

Sry for the long text... short yes/no answers are enough ;-)

**Comment by MrSaints** [comment]
@fsauter, I believe `wicked_pdf` is using `wkhtmltopdf` behind the scenes, and they have support for headers / footers. How it actually works, I'm not too sure. I haven't looked into it. But, that's not something Athena has at the moment.

In theory, if you know exactly how many pages you'll have, you can generate the headers / footers in the same HTML as your main content (using the code I included above).

**Comment by carvilsi** [comment]
Hi all,
Just to say thanks to @MrSaints for this nice workaround and small comment, if you are going to use `pdftk` to merge both PDFs you can avoid the use of GhostScript to count pages and also use `pdftk` for this:
```bashscript
pdftk myPDF.pdf dump_data | grep NumberOfPages | cut -d" " -f 2
```

**Comment by adebali** [comment]
`pdftk` breaks all links though. 

I wonder if anyone has a workaround that doesn't break the links.
